services:
  fastapi_app:
    build:
      context: .
      args:
          PORT_API: 8000
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo_app
      - mysql_app
      - rabbitmq_app
    env_file:
      - .env
    volumes:
      - .:/app

  mongo_app:
    image: mongo:latest
    container_name: mongo_app
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - .:/app


  mysql_app:
    image: mysql:latest
    container_name: mysql_app
    restart: always
    ports:
      - "${PORT_MYSQL}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - .:/app


  rabbitmq_app:
    image: "rabbitmq:management"
    container_name: rabbitmq_app
    restart: always
    ports:
      - "${PORT_MQ}:5672"
      - "${PORT_MANAGEMENT}:15672"
    volumes:
      - .:/app


  consumer_app:
    build:
      context: .
    container_name: consumer_app
    command: sh -c "sleep 10 && python rabbit_mq/consumer.py"
    depends_on:
      - rabbitmq_app
    environment:
      - DOMAIN=rabbitmq_app
      - FILA=ids_mongo
      - PYTHONUNBUFFERED=1
    volumes:
       - .:/app
